apiVersion: v1
kind: Service
metadata:
  name: frontoffice-be-svc
  namespace: frontoffice
  labels:
    app: frontoffice-be
    service: frontoffice-be-svc
spec:
  ports:
    - port: 3002
      targetPort: 3002
      name: tcp
  selector:
    app: frontoffice-be
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontoffice-ksa
  namespace: frontoffice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontoffice-be
  namespace: frontoffice
  labels:
    app: frontoffice-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontoffice-be
  template:
    metadata:
      labels:
        app: frontoffice-be
    spec:
      automountServiceAccountToken: false
      serviceAccountName: frontoffice-ksa
      containers:
        - name: frontoffice-be
          image: asia.gcr.io/aif-staging/frontoffice-be
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          env:
            - name: FO_APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_APP_ENV
            - name: FO_FRONTEND_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_FRONTEND_BASE_URL
            - name: CLOUD_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: CLOUD_PROVIDER
            - name: FO_APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_APP_PORT
            - name: SLACK_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: SLACK_TOKEN
            - name: SLACK_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: SLACK_CHANNEL
            - name: FO_MAILJET_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_MAILJET_EMAIL
            - name: FO_MAILJET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: frontoffice-be-secret
                  key: FO_MAILJET_USERNAME
            - name: FO_MAILJET_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: frontoffice-be-secret
                  key: FO_MAILJET_PUBLIC_KEY
            - name: FO_MAILJET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: frontoffice-be-secret
                  key: FO_MAILJET_SECRET_KEY
            - name: FO_JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_JWT_SECRET_KEY
            - name: FO_JWT_EXPIRES_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_JWT_EXPIRES_MINUTES
            - name: FO_JWT_REFRESH_EXPIRES_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_JWT_REFRESH_EXPIRES_MINUTES
            - name: FO_JWT_RESET_PASSWORD_EXPIRES_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_JWT_RESET_PASSWORD_EXPIRES_MINUTES
            - name: FO_JWT_VERIFICATION_EXPIRES_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_JWT_VERIFICATION_EXPIRES_MINUTES
            - name: FO_JWT_ACTIVATION_EXPIRES_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_JWT_ACTIVATION_EXPIRES_MINUTES
            - name: FO_CORE_HOST
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_CORE_HOST
            - name: FO_CORE_KEY
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_CORE_KEY
            - name: FO_DATAHUB_HOST
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_DATAHUB_HOST
            - name: FO_SCOREEZY_HOST
              valueFrom:
                configMapKeyRef:
                  name: frontoffice-be-config
                  key: FO_SCOREEZY_HOST

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontoffice-be-hpa
  namespace: frontoffice
  labels:
    app: frontoffice-be
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontoffice-be
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
